language: python
python: 
 - 3.6
addons:
  apt_packages:
    # needed for building documentation of jupyter notebooks
    - pandoc

install:
 - pip install --upgrade pip
 - pip install -e .[doc]

script:
 - 'python -m unittest discover'
 - 'cd doc; bash make_doc.sh'
